### ISSUE TITLE
[Cata] 4.4.1 breaks it a little

### ISSUE THREAD

**Issue by Road-block** [verkkila/TransmogOutfitManager#4]
So Blizzard enabled their own outfit manager in 4.4.1 so you would think this addon is obsolete.

But **nope!**
Because in typical late Blizzard fashion the built-in one is buggy as hell. 
"You can't save all the appearances in this outfit as your character can't apply" blah blah .. for already applied xmogs.

Aanyway. 

Simple fix to GetMouseFocus() removal so this keeps working, as well moving the Outfits button/inputbox/save button so they're not hidden behind the default ones.

```lua
local GetMouseFocus = function()
	if _G.GetMouseFocus then
		return _G.GetMouseFocus()
	elseif _G.GetMouseFoci then
		return _G.GetMouseFoci()[1] -- topmost
	end
end
```
at the top of TOMDisplayFrames.lua

and
```lua
TOM.Input.OutfitsButton = CreateFrame("Button", nil, WardrobeFrame, "UIPanelButtonTemplate")
TOM.Input.OutfitsButton:ClearAllPoints()
TOM.Input.OutfitsButton:SetPoint("TOPLEFT", 63, -35)
TOM.Input.OutfitsButton:SetSize(60, 25)
TOM.Input.OutfitsButton:SetText("Outfits")

TOM.Input.OutfitNameBox = CreateFrame("EditBox", nil, WardrobeFrame, "InputBoxTemplate")
TOM.Input.OutfitNameBox:ClearAllPoints()
TOM.Input.OutfitNameBox:SetPoint("TOPLEFT", 130, -30)
TOM.Input.OutfitNameBox:SetSize(113, 35)
TOM.Input.OutfitNameBox:SetAutoFocus(false)

TOM.Input.SaveOutfitButton = CreateFrame("Button", nil, WardrobeFrame, "UIPanelButtonTemplate")
TOM.Input.SaveOutfitButton:ClearAllPoints()
TOM.Input.SaveOutfitButton:SetPoint("TOPLEFT", 245, -35)
TOM.Input.SaveOutfitButton:SetSize(60, 25)
TOM.Input.SaveOutfitButton:SetText("Save")
```
for TOMInputFrames.lua

**Comment by verkkila** [comment]
Hi, I wasn't subscribed to the game for a while during summer. However, I am now so I will take a look at the current situation and patch the things that are needed. Thanks for the info!

**Comment by Road-block** [comment]
Thanks for fix.
